archive = "bionic"
version = "18.04"
origin = "system76-curated-free"
label = "System76 Curated Free Software"
email = "michael@system76.com"

[[repos]]
repo = "http://ppa.launchpad.net/js-reynaud/kicad-5/ubuntu/pool/main/"
version = { is = "ubuntu18.04" }
arch = { is = "all|amd64" }
name = { not = "dbg"}

[[repos]]
repo = "http://ppa.launchpad.net/freecad-maintainers/freecad-stable/ubuntu/pool/main/"
version = { is = "ubuntu18.04" }
arch = { is = "all|amd64" }

# Peek GTK application
[[repos]]
repo = "http://ppa.launchpad.net/peek-developers/stable/ubuntu/pool/main/"
version = { is = "ubuntu18.04" }
arch = { is = "all|amd64"}

# Updated stable scribus (1.4.x), and scribus-ng (1.5.x)
[[repos]]
repo = "http://ppa.launchpad.net/scribus/ppa/ubuntu/pool/main/"
version = { is = "ubuntu18.04" }
arch = { is = "all|amd64" }
name = { not = "dbg"}

[[direct]]
name = "atom"
version = "1.35.1"

    [[direct.urls]]
    url = "https://github.com/${name}/${name}/releases/download/v${version}/${name}-amd64.deb"
    checksum = "9e6a98e0557169cceb299c3cc6cf20e416c0c12c605caedac74cd10ee147529e"

[[direct]]
name = "mattermost-desktop"
version = "4.2.0"

    [[direct.urls]]
    url = "https://releases.mattermost.com/desktop/${version}/${name}-${version}-linux-amd64.deb"
    checksum = "80c7f875b3271bf68161be18cab88e71b73985cd67931c62f7da969d2cd78df2"

[[direct]]
name = "wire-desktop"
version = "3.7.2891"

    [[direct.urls]]
    url = "https://github.com/wireapp/wire-desktop/releases/download/linux%2F${version}/Wire-${version}_amd64.deb"
    checksum = "0c7f16c951b47c570d0f7ddea192a84552e0400e90043b20888aa77c73e89674"

[[direct]]
name = "github-desktop"
version = "1.4.2-linux1"

    [[direct.urls]]
    arch = "amd64"
    url = "https://github.com/shiftkey/desktop/releases/download/release-${version}/GitHubDesktop-linux-amd64-${version}.deb"
    checksum = "1707e8ec012c48677b5a8735fad5546d5e1406a8afe81fe59bc2429fbc242986"

[[source]]
name = "piserver"
build_on = "changelog"

    [source.location]
    git = "https://github.com/raspberrypi/piserver"
