archive = "cosmic"
version = "18.10"
origin = "system76-curated-free"
label = "System76 Curated Free Software"
email = "info@system76.com"

[[repos]]
repo = "http://ppa.launchpad.net/js-reynaud/kicad-5/ubuntu/pool/main/"
version = { is = "ubuntu18.10" }
arch = { is = "amd64|all" }

# Peek GTK application
[[repos]]
repo = "http://ppa.launchpad.net/peek-developers/stable/ubuntu/pool/main/"
version = { is = "ubuntu18.10" }
arch = { is = "amd64|all" }

# Updated thunderbird packages, and firefox-esr
[[repos]]
repo = "http://ppa.launchpad.net/mozillateam/ppa/ubuntu/pool/main/"
version = { is = "18.10" }
arch = { is = "amd64|all" }

# Updated stable scribus (1.4.x), and scribus-ng (1.5.x)
[[repos]]
repo = "http://ppa.launchpad.net/scribus/ppa/ubuntu/pool/main/"
version = { is = "ubuntu18.10" }
arch = { is = "amd64|all" }

# # Updated MPV packages built with vapoursynth support
# [[repos]]
# repo = "http://ppa.launchpad.net/djcj/vapoursynth/ubuntu/pool/main/"
# version = { is = "bionic" }

# # Updated GIMP packages
# [[repos]]
# repo = "http://ppa.launchpad.net/otto-kesselgulasch/gimp/ubuntu/pool/main/"
# version = { is = "18.04" }

# # Updated Krita packages
# [[repos]]
# repo = "http://ppa.launchpad.net/kritalime/ppa/ubuntu/pool/main/"
# version = { is = "bionic|18.04" }

[[direct]]
name = "atom"
version = "1.32.1"

    [[direct.urls]]
    url = "https://github.com/${name}/${name}/releases/download/v${version}/${name}-amd64.deb"
    checksum = "094fc7f64bd276946c57dbcf0ce83ee25c9cc027ff6c80774d1c3fb5e19242f4"

[[direct]]
name = "mattermost-desktop"
version = "4.1.2"

    [[direct.urls]]
    url = "https://releases.mattermost.com/desktop/${version}/${name}-${version}-linux-amd64.deb"
    checksum = "9c53abf8b2e50d9eae02cb1cbebe0e006091388c7ce49d26f95b93e2a7df6ffb"

[[direct]]
name = "wire-desktop"
version = "3.3.2872"

    [[direct.urls]]
    url = "https://github.com/wireapp/${name}/releases/download/release/${version}/wire_${version}_amd64.deb"
    checksum = "fca2cabdd934dca956525b60f97dd2712120499c7f10b10259fe4701439ada13"

[[direct]]
name = "github-desktop"
version = "1.4.2-linux1"

    [[direct.urls]]
    url = "https://github.com/shiftkey/desktop/releases/download/release-${version}/GitHubDesktop-linux-amd64-${version}.deb"
    checksum = "1707e8ec012c48677b5a8735fad5546d5e1406a8afe81fe59bc2429fbc242986"

[[source]]
name = "piserver"
build_on = "changelog"

    [source.location]
    git = "https://github.com/raspberrypi/piserver"
