archive = "cosmic"
version = "18.10"
origin = "system76-curated-free"
label = "System76 Curated Free Software"
email = "info@system76.com"

[[repos]]
repo = "http://ppa.launchpad.net/js-reynaud/kicad-5/ubuntu/pool/main/"
version = { is = "ubuntu18.10" }
arch = { is = "amd64|all" }
name = { not = "dbg"}

# Updated stable scribus (1.4.x), and scribus-ng (1.5.x)
[[repos]]
repo = "http://ppa.launchpad.net/scribus/ppa/ubuntu/pool/main/"
version = { is = "ubuntu18.10" }
arch = { is = "amd64|all" }
name = { not = "dbg" }

[[direct]]
name = "atom"
version = "1.34.0"

    [[direct.urls]]
    url = "https://github.com/${name}/${name}/releases/download/v${version}/${name}-amd64.deb"
    checksum = "6bd2df54344c7e4a058f6571f63ba32c732e393b33b3eccefb711096ab97199a"

[[direct]]
name = "mattermost-desktop"
version = "4.2.0"

    [[direct.urls]]
    url = "https://releases.mattermost.com/desktop/${version}/${name}-${version}-linux-amd64.deb"
    checksum = "80c7f875b3271bf68161be18cab88e71b73985cd67931c62f7da969d2cd78df2"

[[direct]]
name = "wire-desktop"
version = "3.6.2885"

    [[direct.urls]]
    url = "https://github.com/wireapp/wire-desktop/releases/download/linux%2F${version}/Wire-${version}-amd64.deb"
    checksum = "3bedda4d8fb640c0f3a0f65a89258dfe788dc0e3d686db7ebe6a6ce4af4388b6"

[[direct]]
name = "github-desktop"
version = "1.4.2-linux1"

    [[direct.urls]]
    arch = "amd64"
    url = "https://github.com/shiftkey/desktop/releases/download/release-${version}/GitHubDesktop-linux-amd64-${version}.deb"
    checksum = "1707e8ec012c48677b5a8735fad5546d5e1406a8afe81fe59bc2429fbc242986"

[[source]]
name = "piserver"
build_on = "changelog"

    [source.location]
    git = "https://github.com/raspberrypi/piserver"
