archive = "disco"
version = "19.04"
origin = "system76-curated-free"
label = "System76 Curated Free Software"
email = "info@system76.com"

# Updated thunderbird packages, and firefox-esr
[[repos]]
repo = "http://ppa.launchpad.net/mozillateam/ppa/ubuntu/pool/main/"
version = { is = "19.04" }
arch = { is = "amd64|all" }

[[direct]]
name = "atom"
version = "1.33.0"

    [[direct.urls]]
    url = "https://github.com/${name}/${name}/releases/download/v${version}/${name}-amd64.deb"
    checksum = "59b04ef93354768b27978d8e97e91faae87155a4d1df18021e95a4fff837d538"

[[direct]]
name = "mattermost-desktop"
version = "4.2.0"

    [[direct.urls]]
    url = "https://releases.mattermost.com/desktop/${version}/${name}-${version}-linux-amd64.deb"
    checksum = "80c7f875b3271bf68161be18cab88e71b73985cd67931c62f7da969d2cd78df2"

[[direct]]
name = "wire-desktop"
version = "3.4.2879"

    [[direct.urls]]
    url = "https://github.com/wireapp/${name}/releases/download/release/${version}/wire_${version}_amd64.deb"
    checksum = "2d95f2aa0eac6d55cbcc3851e39e708f310d229c75d5ea919767e1bd075f67b4"

[[direct]]
name = "github-desktop"
version = "1.4.2-linux1"

    [[direct.urls]]
    arch = "amd64"
    url = "https://github.com/shiftkey/desktop/releases/download/release-${version}/GitHubDesktop-linux-amd64-${version}.deb"
    checksum = "1707e8ec012c48677b5a8735fad5546d5e1406a8afe81fe59bc2429fbc242986"

[[source]]
name = "piserver"
build_on = "changelog"

    [source.location]
    git = "https://github.com/raspberrypi/piserver"
