archive = "groovy"
version = "20.10"
origin = "system76-curated-free"
label = "System76 Curated Free Software"
email = "info@system76.com"

[[direct]]
name = "atom"
version = "1.53.0-beta0"

    [[direct.urls]]
    url = "https://github.com/atom/atom/releases/download/v1.53.0-beta0/atom-amd64.deb"
    checksum = "d933b98d1fcf189803ee33753b87ba150db95cb8cf781efb95b484a47817f025"

[[direct]]
name = "github-desktop"
version = "2.4.1-linux1"

    [[direct.urls]]
    arch = "amd64"
    url = "https://github.com/shiftkey/desktop/releases/download/release-${version}/GitHubDesktop-linux-${version}.deb"
    checksum = "5339a240b549656cfcf948d98002f03842914d7eaa6ed0548e352e30ffa4b683"

# [[source]]
# name = "piserver"
# build_on = "changelog"

#     [source.location]
#     git = "https://github.com/raspberrypi/piserver"
